spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: false